//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.image` struct is generated, and contains static references to 11 images.
  struct image {
    /// Image `LaunchImage`.
    static let launchImage = Rswift.ImageResource(bundle: R.hostingBundle, name: "LaunchImage")
    /// Image `tabbar_icon_faxain_default`.
    static let tabbar_icon_faxain_default = Rswift.ImageResource(bundle: R.hostingBundle, name: "tabbar_icon_faxain_default")
    /// Image `tabbar_icon_faxain_selected`.
    static let tabbar_icon_faxain_selected = Rswift.ImageResource(bundle: R.hostingBundle, name: "tabbar_icon_faxain_selected")
    /// Image `tabbar_icon_main_default`.
    static let tabbar_icon_main_default = Rswift.ImageResource(bundle: R.hostingBundle, name: "tabbar_icon_main_default")
    /// Image `tabbar_icon_main_selected`.
    static let tabbar_icon_main_selected = Rswift.ImageResource(bundle: R.hostingBundle, name: "tabbar_icon_main_selected")
    /// Image `tabbar_icon_tianwang_default`.
    static let tabbar_icon_tianwang_default = Rswift.ImageResource(bundle: R.hostingBundle, name: "tabbar_icon_tianwang_default")
    /// Image `tabbar_icon_tianwang_selected`.
    static let tabbar_icon_tianwang_selected = Rswift.ImageResource(bundle: R.hostingBundle, name: "tabbar_icon_tianwang_selected")
    /// Image `tabbar_icon_xiaoxi_default`.
    static let tabbar_icon_xiaoxi_default = Rswift.ImageResource(bundle: R.hostingBundle, name: "tabbar_icon_xiaoxi_default")
    /// Image `tabbar_icon_xiaoxi_selected`.
    static let tabbar_icon_xiaoxi_selected = Rswift.ImageResource(bundle: R.hostingBundle, name: "tabbar_icon_xiaoxi_selected")
    /// Image `tabbar_icon_yingyong_default`.
    static let tabbar_icon_yingyong_default = Rswift.ImageResource(bundle: R.hostingBundle, name: "tabbar_icon_yingyong_default")
    /// Image `tabbar_icon_yingyong_selected`.
    static let tabbar_icon_yingyong_selected = Rswift.ImageResource(bundle: R.hostingBundle, name: "tabbar_icon_yingyong_selected")
    
    /// `UIImage(named: "LaunchImage", bundle: ..., traitCollection: ...)`
    static func launchImage(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.launchImage, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_icon_faxain_default", bundle: ..., traitCollection: ...)`
    static func tabbar_icon_faxain_default(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.tabbar_icon_faxain_default, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_icon_faxain_selected", bundle: ..., traitCollection: ...)`
    static func tabbar_icon_faxain_selected(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.tabbar_icon_faxain_selected, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_icon_main_default", bundle: ..., traitCollection: ...)`
    static func tabbar_icon_main_default(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.tabbar_icon_main_default, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_icon_main_selected", bundle: ..., traitCollection: ...)`
    static func tabbar_icon_main_selected(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.tabbar_icon_main_selected, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_icon_tianwang_default", bundle: ..., traitCollection: ...)`
    static func tabbar_icon_tianwang_default(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.tabbar_icon_tianwang_default, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_icon_tianwang_selected", bundle: ..., traitCollection: ...)`
    static func tabbar_icon_tianwang_selected(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.tabbar_icon_tianwang_selected, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_icon_xiaoxi_default", bundle: ..., traitCollection: ...)`
    static func tabbar_icon_xiaoxi_default(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.tabbar_icon_xiaoxi_default, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_icon_xiaoxi_selected", bundle: ..., traitCollection: ...)`
    static func tabbar_icon_xiaoxi_selected(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.tabbar_icon_xiaoxi_selected, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_icon_yingyong_default", bundle: ..., traitCollection: ...)`
    static func tabbar_icon_yingyong_default(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.tabbar_icon_yingyong_default, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_icon_yingyong_selected", bundle: ..., traitCollection: ...)`
    static func tabbar_icon_yingyong_selected(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.tabbar_icon_yingyong_selected, compatibleWith: traitCollection)
    }
    
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      // There are no resources to validate
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R {
  fileprivate init() {}
}
